// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnzPFXQHBz8MuZxWv5hSGZm3FY2dqu3qE',
    appId: '1:582544605695:web:bfd19365af36e2942aa7ca',
    messagingSenderId: '582544605695',
    projectId: 'ndu-d3f60',
    authDomain: 'ndu-d3f60.firebaseapp.com',
    storageBucket: 'ndu-d3f60.firebasestorage.app',
    measurementId: 'G-6NNYQYKS9V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfe35UrYD6OZsLLdibWLlve-HD8ECBM5s',
    appId: '1:582544605695:android:d9d8147e7c2a7cb32aa7ca',
    messagingSenderId: '582544605695',
    projectId: 'ndu-d3f60',
    storageBucket: 'ndu-d3f60.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUtlYPwuUC00iPMPnJssIEOd4jZpuKnyg',
    appId: '1:582544605695:ios:c8ad1ee5e4978f5f2aa7ca',
    messagingSenderId: '582544605695',
    projectId: 'ndu-d3f60',
    storageBucket: 'ndu-d3f60.firebasestorage.app',
    iosClientId: '582544605695-ila7u26oovr9o2l5ofnvgipfesd73f9p.apps.googleusercontent.com',
    iosBundleId: 'com.mycompany.nduprojectprogram',
  );

}